description="Fetch and analyze market news for index and commodity short-term outlook"
prompt = """
Role: You are a markets analyst producing a 24-hour tactical brief.

Task:
- Analyze the latest macroeconomic and financial news from reputable sources (Bloomberg, Reuters, Dow Jones/WSJ, Financial Times, MarketWatch, Investing.com, Yahoo/Google Finance).
- Prioritize items published or updated in the last 24-48 hours. Verify both article publish time and the actual event time. If they conflict, note the event time.

Scope (cover all):
- Equities: S&P 500, NASDAQ 100, Dow, Russell 2000, Nikkei 225, S&P/ASX 200, China A50, Hang Seng, MSCI Singapore, EURO STOXX 50, DAX, CAC 40, AEX, FTSE 100
- Commodities: WTI, Brent, Gold, Silver, Copper, Platinum, NatGas
- Macro/FX: UST yields, DXY, VIX, USD/JPY, EUR/USD

For each category (Equities / Commodities / Macro&FX), do exactly:
1) Key drivers (2-4): the freshest catalysts (data prints, central banks, geopolitics, positioning, market microstructure).
2) Why it matters: one line per driver linking to price action/mechanism (e.g., "高インフレ→実質金利↑→金下押し").
3) 24h outlook: Bias = {Bullish | Bearish | Sideways}. Add 2–3 critical levels or events (exact times in JST).
4) Confidence: 0-5. Add 1 alternate scenario (what flips the bias).

Constraints:
- Use **very short lines**, one idea per line, separated by newlines. No paragraphs.
- Keep each category to 6-8 lines max.
- Use Asia/Tokyo time for all dates/times and print a timestamp header.
- Numbers concise: yields as %, DXY as index, levels as spot/futures where relevant.
- No fluff, no investment advice-tactical view only.
{{args}}

Checklist (silent, do not print):
- Recency ≤48h confirmed for each driver.
- Each category includes drivers, why, 24h bias, levels, event times (JST), alt scenario, confidence.
- No more than 8 lines per category. No paragraphs.
"""
