---
name: CI/CD
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
jobs:
  gemini-cli-to-slack:
    uses: ./.github/workflows/github-actions-lint.yml
    with:
      gemini-cli-prompt: 'What is the meaning of life?'
      slack-channel-id: ${{ env.SLACK_CHANNEL_ID }}
      gemini-cli-version: latest
      title: 'Gemini CLI Result :milky_way:'
      fail-on-error: true
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
